// <auto-generated />
using System;
using API_AMOVER.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_AMOVER.Migrations
{
    [DbContext(typeof(LcmContext))]
    [Migration("20260116220512_atualizar bd")]
    partial class atualizarbd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Checklist", b =>
                {
                    b.Property<int>("IDChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklist"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IDChecklist");

                    b.ToTable("Checklist", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistControlo", b =>
                {
                    b.Property<int>("IDChecklistControlo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistControlo"));

                    b.Property<int>("ControloFinal")
                        .HasColumnType("int");

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistControlo");

                    b.HasIndex(new[] { "IDChecklist" }, "IX_ChecklistControlo_IDChecklist");

                    b.HasIndex(new[] { "IDOrdemProducao" }, "IX_ChecklistControlo_IDOrdemProducao");

                    b.ToTable("ChecklistControlo", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistEmbalagem", b =>
                {
                    b.Property<int>("IDChecklistEmbalagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistEmbalagem"));

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<int>("Incluido")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistEmbalagem");

                    b.HasIndex(new[] { "IDChecklist" }, "IX_ChecklistEmbalagem_IDChecklist");

                    b.HasIndex(new[] { "IDOrdemProducao" }, "IX_ChecklistEmbalagem_IDOrdemProducao");

                    b.ToTable("ChecklistEmbalagem", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistModelo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "IDChecklist" }, "IX_ChecklistModelos_IDChecklist");

                    b.HasIndex(new[] { "IDModelo" }, "IX_ChecklistModelos_IDModelo");

                    b.ToTable("ChecklistModelos");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistMontagem", b =>
                {
                    b.Property<int>("IDChecklistMontagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistMontagem"));

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<int>("Verificado")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistMontagem");

                    b.HasIndex(new[] { "IDChecklist" }, "IX_ChecklistMontagem_IDChecklist");

                    b.HasIndex(new[] { "IDOrdemProducao" }, "IX_ChecklistMontagem_IDOrdemProducao");

                    b.ToTable("ChecklistMontagem", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaEncomenda")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Documento", b =>
                {
                    b.Property<int>("IDDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDocumento"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDocumento");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.DocumentosModelo", b =>
                {
                    b.Property<int>("IDDocumentosModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDocumentosModelo"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.HasKey("IDDocumentosModelo");

                    b.HasIndex(new[] { "IDDocumento" }, "IX_DocumentosModelo_IDDocumento");

                    b.HasIndex(new[] { "IDModelo" }, "IX_DocumentosModelo_IDModelo");

                    b.ToTable("DocumentosModelo", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Encomenda", b =>
                {
                    b.Property<int>("IDEncomenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEncomenda"));

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("IDEncomenda");

                    b.HasIndex(new[] { "IDCliente" }, "IX_Encomendas_IDCliente");

                    b.HasIndex(new[] { "IDModelo" }, "IX_Encomendas_IDModelo");

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModeloPecasFixa", b =>
                {
                    b.Property<int>("IDMPF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMPF"));

                    b.Property<string>("EspecificacaoPadrao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.HasKey("IDMPF");

                    b.HasIndex(new[] { "IDModelo" }, "IX_ModeloPecasFixas_IDModelo");

                    b.HasIndex(new[] { "IDPeca" }, "IX_ModeloPecasFixas_IDPeca");

                    b.ToTable("ModeloPecasFixas");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModeloPecasSN", b =>
                {
                    b.Property<int>("IDModeloPSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDModeloPSN"));

                    b.Property<string>("EspecificacaoPadrao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloMotaIDModelo")
                        .HasColumnType("int");

                    b.HasKey("IDModeloPSN");

                    b.HasIndex(new[] { "IDModelo" }, "IX_ModeloPecasSN_IDModelo");

                    b.HasIndex(new[] { "IDPeca" }, "IX_ModeloPecasSN_IDPeca");

                    b.HasIndex(new[] { "ModeloMotaIDModelo" }, "IX_ModeloPecasSN_ModeloMotaIDModelo");

                    b.ToTable("ModeloPecasSN", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModelosMotum", b =>
                {
                    b.Property<int>("IDModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDModelo"));

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataDescontinuacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioProducao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDModelo");

                    b.ToTable("ModelosMota");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Mota", b =>
                {
                    b.Property<int>("IDMota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMota"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<string>("NumeroIdentificacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<double>("Quilometragem")
                        .HasColumnType("float");

                    b.HasKey("IDMota");

                    b.HasIndex(new[] { "IDModelo" }, "IX_Motas_IDModelo");

                    b.HasIndex(new[] { "IDOrdemProducao" }, "IX_Motas_IDOrdemProducao")
                        .IsUnique();

                    b.ToTable("Motas");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.MotasPecasInfo", b =>
                {
                    b.Property<int>("IDMotasPecasInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMotasPecasInfo"));

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMotasPecasInfo");

                    b.HasIndex(new[] { "IDMota" }, "IX_MotasPecasInfo_IDMota");

                    b.HasIndex(new[] { "IDPeca" }, "IX_MotasPecasInfo_IDPeca");

                    b.ToTable("MotasPecasInfo", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.MotasPecasSN", b =>
                {
                    b.Property<int>("IDMotasPecasSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMotasPecasSN"));

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMotasPecasSN");

                    b.HasIndex(new[] { "IDMota" }, "IX_MotasPecasSN_IDMota");

                    b.HasIndex(new[] { "IDPeca" }, "IX_MotasPecasSN_IDPeca");

                    b.ToTable("MotasPecasSN", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.OrdemProducao", b =>
                {
                    b.Property<int>("IDOrdemProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOrdemProducao"));

                    b.Property<int?>("ClienteIDCliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncomendaIDEncomenda")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDEncomenda")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloMotaIDModelo")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOrdem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDOrdemProducao");

                    b.HasIndex(new[] { "ClienteIDCliente" }, "IX_OrdemProducao_ClienteIDCliente");

                    b.HasIndex(new[] { "EncomendaIDEncomenda" }, "IX_OrdemProducao_EncomendaIDEncomenda");

                    b.HasIndex(new[] { "IDEncomenda" }, "IX_OrdemProducao_IDEncomenda");

                    b.HasIndex(new[] { "ModeloMotaIDModelo" }, "IX_OrdemProducao_ModeloMotaIDModelo");

                    b.ToTable("OrdemProducao", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Peca", b =>
                {
                    b.Property<int>("IDPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPeca"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPeca");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Servico", b =>
                {
                    b.Property<int>("IDServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDServico"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<string>("NotasServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IDServico");

                    b.HasIndex(new[] { "IDMota" }, "IX_Servico_IDMota");

                    b.ToTable("Servico", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ServicosPecasAlterada", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IDMotasPecasSN")
                        .HasColumnType("int");

                    b.Property<int>("IDServico")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "IDMotasPecasSN" }, "IX_ServicosPecasAlteradas_IDMotasPecasSN");

                    b.HasIndex(new[] { "IDServico" }, "IX_ServicosPecasAlteradas_IDServico");

                    b.ToTable("ServicosPecasAlteradas");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.UtilizadorMotum", b =>
                {
                    b.Property<int>("IDUtilizadorMota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUtilizadorMota"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("MotivoInativacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtilizadorMota");

                    b.HasIndex(new[] { "IDMota" }, "IX_UtilizadorMota_IDMota");

                    b.HasIndex(new[] { "IdUtilizador" }, "IX_UtilizadorMota_IdUtilizador");

                    b.ToTable("UtilizadorMota");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Utilizadore", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizador"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("KeycloakId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUserToken", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistControlo", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Checklist", "IDChecklistNavigation")
                        .WithMany("ChecklistControlos")
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.OrdemProducao", "IDOrdemProducaoNavigation")
                        .WithMany("ChecklistControlos")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDChecklistNavigation");

                    b.Navigation("IDOrdemProducaoNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistEmbalagem", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Checklist", "IDChecklistNavigation")
                        .WithMany("ChecklistEmbalagems")
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.OrdemProducao", "IDOrdemProducaoNavigation")
                        .WithMany("ChecklistEmbalagems")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDChecklistNavigation");

                    b.Navigation("IDOrdemProducaoNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistModelo", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Checklist", "IDChecklistNavigation")
                        .WithMany("ChecklistModelos")
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "IDModeloNavigation")
                        .WithMany("ChecklistModelos")
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDChecklistNavigation");

                    b.Navigation("IDModeloNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ChecklistMontagem", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Checklist", "IDChecklistNavigation")
                        .WithMany("ChecklistMontagems")
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.OrdemProducao", "IDOrdemProducaoNavigation")
                        .WithMany("ChecklistMontagems")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDChecklistNavigation");

                    b.Navigation("IDOrdemProducaoNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.DocumentosModelo", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Documento", "Documento")
                        .WithMany("DocumentosModelos")
                        .HasForeignKey("IDDocumento")
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "Modelo")
                        .WithMany("DocumentosModelos")
                        .HasForeignKey("IDModelo")
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Encomenda", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Cliente", "IDClienteNavigation")
                        .WithMany("Encomenda")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "IDModeloNavigation")
                        .WithMany("Encomenda")
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDClienteNavigation");

                    b.Navigation("IDModeloNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModeloPecasFixa", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "IDModeloNavigation")
                        .WithMany("ModeloPecasFixas")
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Peca", "IDPecaNavigation")
                        .WithMany("ModeloPecasFixas")
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDModeloNavigation");

                    b.Navigation("IDPecaNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModeloPecasSN", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "IDModeloNavigation")
                        .WithMany("ModeloPecasSNIDModeloNavigations")
                        .HasForeignKey("IDModelo")
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Peca", "IDPecaNavigation")
                        .WithMany("ModeloPecasSNs")
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "ModeloMotaIDModeloNavigation")
                        .WithMany("ModeloPecasSNModeloMotaIDModeloNavigations")
                        .HasForeignKey("ModeloMotaIDModelo");

                    b.Navigation("IDModeloNavigation");

                    b.Navigation("IDPecaNavigation");

                    b.Navigation("ModeloMotaIDModeloNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Mota", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "IDModeloNavigation")
                        .WithMany("Mota")
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.OrdemProducao", "IDOrdemProducaoNavigation")
                        .WithOne("Mota")
                        .HasForeignKey("API_AMOVER.Data.Models.Mota", "IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDModeloNavigation");

                    b.Navigation("IDOrdemProducaoNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.MotasPecasInfo", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Mota", "IDMotaNavigation")
                        .WithMany("MotasPecasInfos")
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Peca", "IDPecaNavigation")
                        .WithMany("MotasPecasInfos")
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDMotaNavigation");

                    b.Navigation("IDPecaNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.MotasPecasSN", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Mota", "IDMotaNavigation")
                        .WithMany("MotasPecasSNs")
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Peca", "IDPecaNavigation")
                        .WithMany("MotasPecasSNs")
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDMotaNavigation");

                    b.Navigation("IDPecaNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.OrdemProducao", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Cliente", "ClienteIDClienteNavigation")
                        .WithMany("OrdemProducaos")
                        .HasForeignKey("ClienteIDCliente");

                    b.HasOne("API_AMOVER.Data.Models.Encomenda", "EncomendaIDEncomendaNavigation")
                        .WithMany("OrdemProducaoEncomendaIDEncomendaNavigations")
                        .HasForeignKey("EncomendaIDEncomenda");

                    b.HasOne("API_AMOVER.Data.Models.Encomenda", "IDEncomendaNavigation")
                        .WithMany("OrdemProducaoIDEncomendaNavigations")
                        .HasForeignKey("IDEncomenda")
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.ModelosMotum", "ModeloMotaIDModeloNavigation")
                        .WithMany("OrdemProducaos")
                        .HasForeignKey("ModeloMotaIDModelo");

                    b.Navigation("ClienteIDClienteNavigation");

                    b.Navigation("EncomendaIDEncomendaNavigation");

                    b.Navigation("IDEncomendaNavigation");

                    b.Navigation("ModeloMotaIDModeloNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Servico", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Mota", "IDMotaNavigation")
                        .WithMany("Servicos")
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDMotaNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ServicosPecasAlterada", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.MotasPecasSN", "IDMotasPecasSNNavigation")
                        .WithMany("ServicosPecasAlterada")
                        .HasForeignKey("IDMotasPecasSN")
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Servico", "IDServicoNavigation")
                        .WithMany("ServicosPecasAlterada")
                        .HasForeignKey("IDServico")
                        .IsRequired();

                    b.Navigation("IDMotasPecasSNNavigation");

                    b.Navigation("IDServicoNavigation");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.UtilizadorMotum", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.Mota", "IDMotaNavigation")
                        .WithMany("UtilizadorMota")
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.Utilizadore", "IdUtilizadorNavigation")
                        .WithMany("UtilizadorMota")
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDMotaNavigation");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("API_AMOVER.Data.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AMOVER.Data.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Checklist", b =>
                {
                    b.Navigation("ChecklistControlos");

                    b.Navigation("ChecklistEmbalagems");

                    b.Navigation("ChecklistModelos");

                    b.Navigation("ChecklistMontagems");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Cliente", b =>
                {
                    b.Navigation("Encomenda");

                    b.Navigation("OrdemProducaos");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Documento", b =>
                {
                    b.Navigation("DocumentosModelos");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Encomenda", b =>
                {
                    b.Navigation("OrdemProducaoEncomendaIDEncomendaNavigations");

                    b.Navigation("OrdemProducaoIDEncomendaNavigations");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.ModelosMotum", b =>
                {
                    b.Navigation("ChecklistModelos");

                    b.Navigation("DocumentosModelos");

                    b.Navigation("Encomenda");

                    b.Navigation("ModeloPecasFixas");

                    b.Navigation("ModeloPecasSNIDModeloNavigations");

                    b.Navigation("ModeloPecasSNModeloMotaIDModeloNavigations");

                    b.Navigation("Mota");

                    b.Navigation("OrdemProducaos");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Mota", b =>
                {
                    b.Navigation("MotasPecasInfos");

                    b.Navigation("MotasPecasSNs");

                    b.Navigation("Servicos");

                    b.Navigation("UtilizadorMota");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.MotasPecasSN", b =>
                {
                    b.Navigation("ServicosPecasAlterada");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.OrdemProducao", b =>
                {
                    b.Navigation("ChecklistControlos");

                    b.Navigation("ChecklistEmbalagems");

                    b.Navigation("ChecklistMontagems");

                    b.Navigation("Mota");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Peca", b =>
                {
                    b.Navigation("ModeloPecasFixas");

                    b.Navigation("ModeloPecasSNs");

                    b.Navigation("MotasPecasInfos");

                    b.Navigation("MotasPecasSNs");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Servico", b =>
                {
                    b.Navigation("ServicosPecasAlterada");
                });

            modelBuilder.Entity("API_AMOVER.Data.Models.Utilizadore", b =>
                {
                    b.Navigation("UtilizadorMota");
                });
#pragma warning restore 612, 618
        }
    }
}
